version: "3.9"
services:
  ingress:
    container_name: playtime_ingress
    build: ./ingress
    ports:
      - 80:80

  mickey:
    container_name: playtime_mickey
    image: nginx:1.21
    ports:
      - 3210:80
    volumes:
      - ${PWD}/mickey/html:/usr/share/nginx/html